pr2_db_version: "4.14.0"
silva_db_version: "138.1"
database: '/home/thursday/PycharmProjects/natrix_classification_new/classification/database'
scripts: '/home/thursday/PycharmProjects/natrix_classification_new/classification/scripts/'
# mothur parameter
search: "kmer"
method: "wang"
silva_ref: '/home/thursday/PycharmProjects/natrix_classification_new/classification/database/silva_db.138.1.tax'
silva_tax: ' /home/thursday/PycharmProjects/natrix_classification_new/classification/database/silva_db.138.1.fasta'
pr2_ref: '/home/thursday/PycharmProjects/natrix_classification_new/classification/database/pr2db.4.14.0.fasta'
pr2_tax:  '/home/thursday/PycharmProjects/natrix_classification_new/classification/database/pr2db.4.14.0.tax' 
threads: 4
results: '/home/thursday/PycharmProjects/natrix_classification_new/classification/results'
input: '/home/thursday/PycharmProjects/natrix_classification_new/classification/input'

